# Import Required Libraries
Import the necessary libraries, including pandas, numpy, matplotlib.pyplot, train_test_split, DecisionTreeClassifier, and cross_val_score.

In [4]:
# Import Required Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.tree import DecisionTreeClassifier

data_url =  "https://raw.githubusercontent.com/mcnakhaee/palmerpenguins/refs/heads/master/palmerpenguins/data/penguins.csv"
penguins = pd.read_csv(data_url)
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

# Split the Dataset
Use train_test_split to create the training and test sets.

In [6]:
# Define features and target variable
penguins_no_chinstrap = pd.concat([adelie, gentoo])
penguins_no_chinstrap = penguins_no_chinstrap.dropna()

X = penguins_no_chinstrap.loc[:,["bill_length_mm", "body_mass_g"]]
y = penguins_no_chinstrap.loc[:,"species"]

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

NameError: name 'adelie' is not defined

# Cross Validation to Find Best max_depth
Use cross_val_score to perform cross validation on the training set to find the best max_depth value for the DecisionTreeClassifier.

In [ ]:
# Cross Validation to Find Best max_depth

# Define a range of max_depth values to test
max_depth_values = range(1, 21)

# Perform cross-validation for each max_depth value and store the results
cv_scores = []
for max_depth in max_depth_values:
    model = DecisionTreeClassifier(max_depth=max_depth, random_state=42)
    scores = cross_val_score(model, X_train, y_train, cv=5)
    cv_scores.append(scores)

# Plot the cross-validation scores for each max_depth value
plt.figure(figsize=(10, 6))
plt.boxplot(cv_scores, labels=max_depth_values)
plt.xlabel('max_depth')
plt.ylabel('Cross-Validation Score')
plt.title('Cross-Validation Scores for Different max_depth Values')
plt.show()

# Find the best max_depth value based on the mean cross-validation score
mean_cv_scores = [np.mean(scores) for scores in cv_scores]
best_max_depth = max_depth_values[np.argmax(mean_cv_scores)]
print(f'The best max_depth value is: {best_max_depth}')

# Train the final model with the best max_depth value on the training set
final_model = DecisionTreeClassifier(max_depth=best_max_depth, random_state=42)
final_model.fit(X_train, y_train)

# Evaluate the final model on the test set
test_score = final_model.score(X_test, y_test)
print(f'Test set score with best max_depth ({best_max_depth}): {test_score}')

# Box Plot for max_depth Values
Use plt.boxplot to create a series of box plots to examine which max_depth value is best.

In [ ]:
# Box Plot for max_depth Values

# Plot the cross-validation scores for each max_depth value
plt.figure(figsize=(10, 6))
plt.boxplot(cv_scores, labels=max_depth_values)
plt.xlabel('max_depth')
plt.ylabel('Cross-Validation Score')
plt.title('Cross-Validation Scores for Different max_depth Values')
plt.show()

# Find the best max_depth value based on the mean cross-validation score
mean_cv_scores = [np.mean(scores) for scores in cv_scores]
best_max_depth = max_depth_values[np.argmax(mean_cv_scores)]
print(f'The best max_depth value is: {best_max_depth}')

# Train the final model with the best max_depth value on the training set
final_model = DecisionTreeClassifier(max_depth=best_max_depth, random_state=42)
final_model.fit(X_train, y_train)

# Evaluate the final model on the test set
test_score = final_model.score(X_test, y_test)
print(f'Test set score with best max_depth ({best_max_depth}): {test_score}')

# Evaluate Best Model on Test Set
Choose the best max_depth value and test it on the original test set to evaluate the model's generalization error.

In [ ]:
# Evaluate Best Model on Test Set

# Choose the best max_depth value and test it on the original test set to evaluate the model's generalization error

# Train the final model with the best max_depth value on the training set
final_model = DecisionTreeClassifier(max_depth=best_max_depth, random_state=42)
final_model.fit(X_train, y_train)

# Evaluate the final model on the test set
test_score = final_model.score(X_test, y_test)
print(f'Test set score with best max_depth ({best_max_depth}): {test_score}')